
name: test TO condition

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'my name'     
        required: false
      age:
        description: 'age'
        required: false

jobs:
  printInputs:
    runs-on: ubuntu-latest
    if: ( !(contains(github.event.inputs.name, '')) && !(contains(github.event.inputs.age, '')))
    steps:
    - name: check
      run: |
        echo "Log level: ${{ github.event.inputs.name }}"
        echo "Tags: ${{ github.event.inputs.age }}" 
    - name: after
      run: |
        echo "Hoai Phong"
