
name: test workflow_dispatch

on: 
  workflow_dispatch:
    branches:
      - TO-01
    inputs:
      name:
        description: 'my name'     
        required: true
        default: 'hoai phong'
      age:
        description: 'age'
        required: true
        default: '21'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hoang Minh Hoai Phong"
        echo "Log level: ${{ github.event.inputs.name }}"
        echo "Tags: ${{ github.event.inputs.age }}" 
