
name: test TO condition

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'my name'     
        required: false
      age:
        description: 'age'
        required: false

jobs:
  printInputs:
    runs-on: ubuntu-latest
    if: (${{ github.event.inputs.name}} != ' ' && ${{ github.event.inputs.age }} != ' ')
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.name }}"
        echo "Tags: ${{ github.event.inputs.age }}" 
