
name: test TO

on: 
  workflow_dispatch:
    branches:
      - TO-02
    inputs:
      name:
        description: 'my name'     
        required: true
        default: 'hoai dhaldk'
      age:
        description: 'age'
        required: true
        default: '22'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.name }}"
        echo "Tags: ${{ github.event.inputs.age }}" 
